Adding Avatar seperating tts (avatar_api  updated)

diff --git a/avatar/Dockerfile b/avatar/Dockerfile
--- a/avatar/Dockerfile
+++ b/avatar/Dockerfile
@@ -20,7 +20,7 @@ RUN chmod +x install_sadtalker.sh && ./install_sadtalker.sh
 RUN cd /app/SadTalker && bash scripts/download_models.sh  || true
 
 # Clear executable stack for libtorch_cpu.so
-RUN find /usr/local/lib/python3.10/site-packages/torch -name "libtorch_cpu.so" -exec patchelf --clear-execstack {} \;
+RUN find /usr/local/lib/python3.10/site-packages/torch -name "libtorch_cpu.so" -exec patchelf --clear-execstack {} \; || echo "PyTorch not found, skipping patchelf"
 
 
 # Fix numpy compatibility issues in SadTalker
